# Generated by Django 3.1.5 on 2021-01-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tags', to='post.Post'),
        ),
        migrations.DeleteModel(
            name='PostReaction',
        ),
    ]
