# Generated by Django 3.1.5 on 2021-01-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_posts',
            field=models.ManyToManyField(blank=True, related_name='user_disliked', to='post.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='disliked_tags',
            field=models.ManyToManyField(blank=True, related_name='user_disliked', to='post.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to='post.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_tags',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to='post.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
