# Generated by Django 3.1.5 on 2021-01-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210122_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked_posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_posts',
        ),
    ]
